name: Deploy to GitHub Pages

on:
  push:
    paths:
      - './gh-deployment-workflow/index.html'  # Only run when index.html is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:  # Defining environment variables
      BASE_URL: https://niceprog.github.io/Roadmap-DevOps/gh-deployment-workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './'  # Points to the folder containing index.html

      - name: Output deployment URL
        run: echo "The website is deployed at ${{ env.BASE_URL }}"  # Using environment variables
