name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'gh-deployment-workflow/index.html'  # Note the new directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and Deploy to GitHub Pages
        working-directory: gh-deployment-workflow  # Set working directory
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Path to the folder where index.html is located
